/*
Xendit API

Balance API description

API version: 2.0.0
*/

// Code generated by OpenAPI Generator; DO NOT EDIT.

package balance

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	
	common "github.com/kennycyb/xendit-go/common"
	utils "github.com/kennycyb/xendit-go/utils"
)


type BalancesApi interface {

	/*
	GetBalance Get Balance

	Get Balance for a specific account type

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiGetBalanceRequest
	*/
	GetBalance(ctx context.Context) ApiGetBalanceRequest

	// GetBalanceExecute executes the request
	//  @return Balance
	GetBalanceExecute(r ApiGetBalanceRequest) (*Balance, *http.Response, error)
}

// BalancesApiService BalancesApi service
type BalancesApiService struct {
	client common.IClient
}

func NewBalancesApi (client common.IClient) BalancesApi {
	return &BalancesApiService{
		client: client,
	}
}

type ApiGetBalanceRequest struct {
	ctx context.Context
	ApiService BalancesApi
	accountType *string
	forUserId *string
	xIdempotencyKey *string
}

// Account Type
func (r ApiGetBalanceRequest) AccountType(accountType string) ApiGetBalanceRequest {
	r.accountType = &accountType
	return r
}

// For User ID
func (r ApiGetBalanceRequest) ForUserId(forUserId string) ApiGetBalanceRequest {
	r.forUserId = &forUserId
	return r
}

// Idempotency Key
func (r ApiGetBalanceRequest) XIdempotencyKey(xIdempotencyKey string) ApiGetBalanceRequest {
	r.xIdempotencyKey = &xIdempotencyKey
	return r
}

func (r ApiGetBalanceRequest) Execute() (*Balance, *http.Response, error) {
	return r.ApiService.GetBalanceExecute(r)
}

/*
GetBalance Get Balance

Get Balance for a specific account type

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetBalanceRequest
*/
func (a *BalancesApiService) GetBalance(ctx context.Context) ApiGetBalanceRequest {
	return ApiGetBalanceRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return Balance
func (a *BalancesApiService) GetBalanceExecute(r ApiGetBalanceRequest) (*Balance, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []common.FormFile
		localVarReturnValue  *Balance
	)

	localBasePath, err := a.client.GetConfig().ServerURLWithContext(r.ctx, "BalancesApiService.GetBalance")
	if err != nil {
		return localVarReturnValue, nil, common.NewGenericOpenAPIError(nil, err.Error(), nil)
	}

	localVarPath := localBasePath + "/balance"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.accountType == nil {
		return localVarReturnValue, nil, utils.ReportError("accountType is required and must be specified")
	}

	utils.ParameterAddToHeaderOrQuery(localVarQueryParams, "account_type", r.accountType, "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := utils.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := utils.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.forUserId != nil {
		utils.ParameterAddToHeaderOrQuery(localVarHeaderParams, "for-user-id", r.forUserId, "")
	}
	if r.xIdempotencyKey != nil {
		utils.ParameterAddToHeaderOrQuery(localVarHeaderParams, "x-idempotency-key", r.xIdempotencyKey, "")
	}
	req, err := a.client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := common.NewGenericOpenAPIError(localVarBody, localVarHTTPResponse.Status, nil)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.Decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := common.NewGenericOpenAPIError(localVarBody, err.Error(), nil)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
