/*
Charge

This API is used for Charge

API version: 1.31.0
*/

// Code generated by OpenAPI Generator; DO NOT EDIT.

package paymentrequest

import (
	"encoding/json"
	
	
	utils "github.com/kennycyb/xendit-go/utils"
	
)

// checks if the MutableCard type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &MutableCard{}

// MutableCard struct for MutableCard
type MutableCard struct {
	ChannelProperties *CardChannelProperties `json:"channel_properties,omitempty"`
	CardInformation *CardInformation `json:"card_information,omitempty"`
	CardVerificationResults NullableCardVerificationResults `json:"card_verification_results,omitempty"`
}

// NewMutableCard instantiates a new MutableCard object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMutableCard() *MutableCard {
	this := MutableCard{}
	return &this
}

// NewMutableCardWithDefaults instantiates a new MutableCard object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMutableCardWithDefaults() *MutableCard {
	this := MutableCard{}
	return &this
}

// GetChannelProperties returns the ChannelProperties field value if set, zero value otherwise.
func (o *MutableCard) GetChannelProperties() CardChannelProperties {
	if o == nil || utils.IsNil(o.ChannelProperties) {
		var ret CardChannelProperties
		return ret
	}
	return *o.ChannelProperties
}

// GetChannelPropertiesOk returns a tuple with the ChannelProperties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MutableCard) GetChannelPropertiesOk() (*CardChannelProperties, bool) {
	if o == nil || utils.IsNil(o.ChannelProperties) {
		return nil, false
	}
	return o.ChannelProperties, true
}

// HasChannelProperties returns a boolean if a field has been set.
func (o *MutableCard) HasChannelProperties() bool {
	if o != nil && !utils.IsNil(o.ChannelProperties) {
		return true
	}

	return false
}

// SetChannelProperties gets a reference to the given CardChannelProperties and assigns it to the ChannelProperties field.
func (o *MutableCard) SetChannelProperties(v CardChannelProperties) {
	o.ChannelProperties = &v
}

// GetCardInformation returns the CardInformation field value if set, zero value otherwise.
func (o *MutableCard) GetCardInformation() CardInformation {
	if o == nil || utils.IsNil(o.CardInformation) {
		var ret CardInformation
		return ret
	}
	return *o.CardInformation
}

// GetCardInformationOk returns a tuple with the CardInformation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MutableCard) GetCardInformationOk() (*CardInformation, bool) {
	if o == nil || utils.IsNil(o.CardInformation) {
		return nil, false
	}
	return o.CardInformation, true
}

// HasCardInformation returns a boolean if a field has been set.
func (o *MutableCard) HasCardInformation() bool {
	if o != nil && !utils.IsNil(o.CardInformation) {
		return true
	}

	return false
}

// SetCardInformation gets a reference to the given CardInformation and assigns it to the CardInformation field.
func (o *MutableCard) SetCardInformation(v CardInformation) {
	o.CardInformation = &v
}

// GetCardVerificationResults returns the CardVerificationResults field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MutableCard) GetCardVerificationResults() CardVerificationResults {
	if o == nil || utils.IsNil(o.CardVerificationResults.Get()) {
		var ret CardVerificationResults
		return ret
	}
	return *o.CardVerificationResults.Get()
}

// GetCardVerificationResultsOk returns a tuple with the CardVerificationResults field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MutableCard) GetCardVerificationResultsOk() (*CardVerificationResults, bool) {
	if o == nil {
		return nil, false
	}
	return o.CardVerificationResults.Get(), o.CardVerificationResults.IsSet()
}

// HasCardVerificationResults returns a boolean if a field has been set.
func (o *MutableCard) HasCardVerificationResults() bool {
	if o != nil && o.CardVerificationResults.IsSet() {
		return true
	}

	return false
}

// SetCardVerificationResults gets a reference to the given NullableCardVerificationResults and assigns it to the CardVerificationResults field.
func (o *MutableCard) SetCardVerificationResults(v CardVerificationResults) {
	o.CardVerificationResults.Set(&v)
}
// SetCardVerificationResultsNil sets the value for CardVerificationResults to be an explicit nil
func (o *MutableCard) SetCardVerificationResultsNil() {
	o.CardVerificationResults.Set(nil)
}

// UnsetCardVerificationResults ensures that no value is present for CardVerificationResults, not even an explicit nil
func (o *MutableCard) UnsetCardVerificationResults() {
	o.CardVerificationResults.Unset()
}

func (o MutableCard) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MutableCard) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.ChannelProperties) {
		toSerialize["channel_properties"] = o.ChannelProperties
	}
	if !utils.IsNil(o.CardInformation) {
		toSerialize["card_information"] = o.CardInformation
	}
	if o.CardVerificationResults.IsSet() {
		toSerialize["card_verification_results"] = o.CardVerificationResults.Get()
	}
	return toSerialize, nil
}

type NullableMutableCard struct {
	value *MutableCard
	isSet bool
}

func (v NullableMutableCard) Get() *MutableCard {
	return v.value
}

func (v *NullableMutableCard) Set(val *MutableCard) {
	v.value = val
	v.isSet = true
}

func (v NullableMutableCard) IsSet() bool {
	return v.isSet
}

func (v *NullableMutableCard) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMutableCard(val *MutableCard) *NullableMutableCard {
	return &NullableMutableCard{value: val, isSet: true}
}

func (v NullableMutableCard) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMutableCard) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


