/*
Charge

This API is used for Charge

API version: 1.31.0
*/

// Code generated by OpenAPI Generator; DO NOT EDIT.

package paymentrequest

import (
	"encoding/json"
	
	
	utils "github.com/kennycyb/xendit-go/utils"
	
)

// checks if the CardChannelProperties type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &CardChannelProperties{}

// CardChannelProperties Card Channel Properties
type CardChannelProperties struct {
	// To indicate whether to perform 3DS during the linking phase
	SkipThreeDSecure *bool `json:"skip_three_d_secure,omitempty"`
	// URL where the end-customer is redirected if the authorization is successful
	SuccessReturnUrl *string `json:"success_return_url,omitempty"`
	// URL where the end-customer is redirected if the authorization failed
	FailureReturnUrl *string `json:"failure_return_url,omitempty"`
	// Type of “credential-on-file” / “card-on-file” payment being made. Indicate that this payment uses a previously linked Payment Method for charging.
	CardonfileType *string `json:"cardonfile_type,omitempty"`
	// Tag for a Merchant ID that you want to associate this payment with. For merchants using their own MIDs to specify which MID they want to use
	MerchantIdTag *string `json:"merchant_id_tag,omitempty"`
}

// NewCardChannelProperties instantiates a new CardChannelProperties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardChannelProperties() *CardChannelProperties {
	this := CardChannelProperties{}
	return &this
}

// NewCardChannelPropertiesWithDefaults instantiates a new CardChannelProperties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardChannelPropertiesWithDefaults() *CardChannelProperties {
	this := CardChannelProperties{}
	return &this
}

// GetSkipThreeDSecure returns the SkipThreeDSecure field value if set, zero value otherwise.
func (o *CardChannelProperties) GetSkipThreeDSecure() bool {
	if o == nil || utils.IsNil(o.SkipThreeDSecure) {
		var ret bool
		return ret
	}
	return *o.SkipThreeDSecure
}

// GetSkipThreeDSecureOk returns a tuple with the SkipThreeDSecure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardChannelProperties) GetSkipThreeDSecureOk() (*bool, bool) {
	if o == nil || utils.IsNil(o.SkipThreeDSecure) {
		return nil, false
	}
	return o.SkipThreeDSecure, true
}

// HasSkipThreeDSecure returns a boolean if a field has been set.
func (o *CardChannelProperties) HasSkipThreeDSecure() bool {
	if o != nil && !utils.IsNil(o.SkipThreeDSecure) {
		return true
	}

	return false
}

// SetSkipThreeDSecure gets a reference to the given bool and assigns it to the SkipThreeDSecure field.
func (o *CardChannelProperties) SetSkipThreeDSecure(v bool) {
	o.SkipThreeDSecure = &v
}

// GetSuccessReturnUrl returns the SuccessReturnUrl field value if set, zero value otherwise.
func (o *CardChannelProperties) GetSuccessReturnUrl() string {
	if o == nil || utils.IsNil(o.SuccessReturnUrl) {
		var ret string
		return ret
	}
	return *o.SuccessReturnUrl
}

// GetSuccessReturnUrlOk returns a tuple with the SuccessReturnUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardChannelProperties) GetSuccessReturnUrlOk() (*string, bool) {
	if o == nil || utils.IsNil(o.SuccessReturnUrl) {
		return nil, false
	}
	return o.SuccessReturnUrl, true
}

// HasSuccessReturnUrl returns a boolean if a field has been set.
func (o *CardChannelProperties) HasSuccessReturnUrl() bool {
	if o != nil && !utils.IsNil(o.SuccessReturnUrl) {
		return true
	}

	return false
}

// SetSuccessReturnUrl gets a reference to the given string and assigns it to the SuccessReturnUrl field.
func (o *CardChannelProperties) SetSuccessReturnUrl(v string) {
	o.SuccessReturnUrl = &v
}

// GetFailureReturnUrl returns the FailureReturnUrl field value if set, zero value otherwise.
func (o *CardChannelProperties) GetFailureReturnUrl() string {
	if o == nil || utils.IsNil(o.FailureReturnUrl) {
		var ret string
		return ret
	}
	return *o.FailureReturnUrl
}

// GetFailureReturnUrlOk returns a tuple with the FailureReturnUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardChannelProperties) GetFailureReturnUrlOk() (*string, bool) {
	if o == nil || utils.IsNil(o.FailureReturnUrl) {
		return nil, false
	}
	return o.FailureReturnUrl, true
}

// HasFailureReturnUrl returns a boolean if a field has been set.
func (o *CardChannelProperties) HasFailureReturnUrl() bool {
	if o != nil && !utils.IsNil(o.FailureReturnUrl) {
		return true
	}

	return false
}

// SetFailureReturnUrl gets a reference to the given string and assigns it to the FailureReturnUrl field.
func (o *CardChannelProperties) SetFailureReturnUrl(v string) {
	o.FailureReturnUrl = &v
}

// GetCardonfileType returns the CardonfileType field value if set, zero value otherwise.
func (o *CardChannelProperties) GetCardonfileType() string {
	if o == nil || utils.IsNil(o.CardonfileType) {
		var ret string
		return ret
	}
	return *o.CardonfileType
}

// GetCardonfileTypeOk returns a tuple with the CardonfileType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardChannelProperties) GetCardonfileTypeOk() (*string, bool) {
	if o == nil || utils.IsNil(o.CardonfileType) {
		return nil, false
	}
	return o.CardonfileType, true
}

// HasCardonfileType returns a boolean if a field has been set.
func (o *CardChannelProperties) HasCardonfileType() bool {
	if o != nil && !utils.IsNil(o.CardonfileType) {
		return true
	}

	return false
}

// SetCardonfileType gets a reference to the given string and assigns it to the CardonfileType field.
func (o *CardChannelProperties) SetCardonfileType(v string) {
	o.CardonfileType = &v
}

// GetMerchantIdTag returns the MerchantIdTag field value if set, zero value otherwise.
func (o *CardChannelProperties) GetMerchantIdTag() string {
	if o == nil || utils.IsNil(o.MerchantIdTag) {
		var ret string
		return ret
	}
	return *o.MerchantIdTag
}

// GetMerchantIdTagOk returns a tuple with the MerchantIdTag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardChannelProperties) GetMerchantIdTagOk() (*string, bool) {
	if o == nil || utils.IsNil(o.MerchantIdTag) {
		return nil, false
	}
	return o.MerchantIdTag, true
}

// HasMerchantIdTag returns a boolean if a field has been set.
func (o *CardChannelProperties) HasMerchantIdTag() bool {
	if o != nil && !utils.IsNil(o.MerchantIdTag) {
		return true
	}

	return false
}

// SetMerchantIdTag gets a reference to the given string and assigns it to the MerchantIdTag field.
func (o *CardChannelProperties) SetMerchantIdTag(v string) {
	o.MerchantIdTag = &v
}

func (o CardChannelProperties) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CardChannelProperties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.SkipThreeDSecure) {
		toSerialize["skip_three_d_secure"] = o.SkipThreeDSecure
	}
	if !utils.IsNil(o.SuccessReturnUrl) {
		toSerialize["success_return_url"] = o.SuccessReturnUrl
	}
	if !utils.IsNil(o.FailureReturnUrl) {
		toSerialize["failure_return_url"] = o.FailureReturnUrl
	}
	if !utils.IsNil(o.CardonfileType) {
		toSerialize["cardonfile_type"] = o.CardonfileType
	}
	if !utils.IsNil(o.MerchantIdTag) {
		toSerialize["merchant_id_tag"] = o.MerchantIdTag
	}
	return toSerialize, nil
}

type NullableCardChannelProperties struct {
	value *CardChannelProperties
	isSet bool
}

func (v NullableCardChannelProperties) Get() *CardChannelProperties {
	return v.value
}

func (v *NullableCardChannelProperties) Set(val *CardChannelProperties) {
	v.value = val
	v.isSet = true
}

func (v NullableCardChannelProperties) IsSet() bool {
	return v.isSet
}

func (v *NullableCardChannelProperties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardChannelProperties(val *CardChannelProperties) *NullableCardChannelProperties {
	return &NullableCardChannelProperties{value: val, isSet: true}
}

func (v NullableCardChannelProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardChannelProperties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


