/*
Payment Method Service v2

This API is used for Payment Method Service v2

API version: 2.79.0
*/

// Code generated by OpenAPI Generator; DO NOT EDIT.

package paymentmethod

import (
	"encoding/json"
	
	
	utils "github.com/kennycyb/xendit-go/utils"
	
)

// checks if the InternalLATLinkedAccountsInner type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &InternalLATLinkedAccountsInner{}

// InternalLATLinkedAccountsInner struct for InternalLATLinkedAccountsInner
type InternalLATLinkedAccountsInner struct {
	Id string `json:"id"`
}

// NewInternalLATLinkedAccountsInner instantiates a new InternalLATLinkedAccountsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInternalLATLinkedAccountsInner(id string) *InternalLATLinkedAccountsInner {
	this := InternalLATLinkedAccountsInner{}
	this.Id = id
	return &this
}

// NewInternalLATLinkedAccountsInnerWithDefaults instantiates a new InternalLATLinkedAccountsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInternalLATLinkedAccountsInnerWithDefaults() *InternalLATLinkedAccountsInner {
	this := InternalLATLinkedAccountsInner{}
	return &this
}

// GetId returns the Id field value
func (o *InternalLATLinkedAccountsInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *InternalLATLinkedAccountsInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *InternalLATLinkedAccountsInner) SetId(v string) {
	o.Id = v
}

func (o InternalLATLinkedAccountsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InternalLATLinkedAccountsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

type NullableInternalLATLinkedAccountsInner struct {
	value *InternalLATLinkedAccountsInner
	isSet bool
}

func (v NullableInternalLATLinkedAccountsInner) Get() *InternalLATLinkedAccountsInner {
	return v.value
}

func (v *NullableInternalLATLinkedAccountsInner) Set(val *InternalLATLinkedAccountsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableInternalLATLinkedAccountsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableInternalLATLinkedAccountsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInternalLATLinkedAccountsInner(val *InternalLATLinkedAccountsInner) *NullableInternalLATLinkedAccountsInner {
	return &NullableInternalLATLinkedAccountsInner{value: val, isSet: true}
}

func (v NullableInternalLATLinkedAccountsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInternalLATLinkedAccountsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


