/*
Payment Method Service v2

This API is used for Payment Method Service v2

API version: 2.79.0
*/

// Code generated by OpenAPI Generator; DO NOT EDIT.

package paymentmethod

import (
	"encoding/json"
	
	
	utils "github.com/kennycyb/xendit-go/utils"
	
)

// checks if the MutableDirectBankTransfer type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &MutableDirectBankTransfer{}

// MutableDirectBankTransfer struct for MutableDirectBankTransfer
type MutableDirectBankTransfer struct {
	ChannelCode DirectBankTransferChannelCode `json:"channel_code"`
	ChannelProperties DirectBankTransferChannelProperties `json:"channel_properties"`
}

// NewMutableDirectBankTransfer instantiates a new MutableDirectBankTransfer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMutableDirectBankTransfer(channelCode DirectBankTransferChannelCode, channelProperties DirectBankTransferChannelProperties) *MutableDirectBankTransfer {
	this := MutableDirectBankTransfer{}
	this.ChannelCode = channelCode
	this.ChannelProperties = channelProperties
	return &this
}

// NewMutableDirectBankTransferWithDefaults instantiates a new MutableDirectBankTransfer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMutableDirectBankTransferWithDefaults() *MutableDirectBankTransfer {
	this := MutableDirectBankTransfer{}
	return &this
}

// GetChannelCode returns the ChannelCode field value
func (o *MutableDirectBankTransfer) GetChannelCode() DirectBankTransferChannelCode {
	if o == nil {
		var ret DirectBankTransferChannelCode
		return ret
	}

	return o.ChannelCode
}

// GetChannelCodeOk returns a tuple with the ChannelCode field value
// and a boolean to check if the value has been set.
func (o *MutableDirectBankTransfer) GetChannelCodeOk() (*DirectBankTransferChannelCode, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelCode, true
}

// SetChannelCode sets field value
func (o *MutableDirectBankTransfer) SetChannelCode(v DirectBankTransferChannelCode) {
	o.ChannelCode = v
}

// GetChannelProperties returns the ChannelProperties field value
func (o *MutableDirectBankTransfer) GetChannelProperties() DirectBankTransferChannelProperties {
	if o == nil {
		var ret DirectBankTransferChannelProperties
		return ret
	}

	return o.ChannelProperties
}

// GetChannelPropertiesOk returns a tuple with the ChannelProperties field value
// and a boolean to check if the value has been set.
func (o *MutableDirectBankTransfer) GetChannelPropertiesOk() (*DirectBankTransferChannelProperties, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelProperties, true
}

// SetChannelProperties sets field value
func (o *MutableDirectBankTransfer) SetChannelProperties(v DirectBankTransferChannelProperties) {
	o.ChannelProperties = v
}

func (o MutableDirectBankTransfer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MutableDirectBankTransfer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["channel_code"] = o.ChannelCode
	toSerialize["channel_properties"] = o.ChannelProperties
	return toSerialize, nil
}

type NullableMutableDirectBankTransfer struct {
	value *MutableDirectBankTransfer
	isSet bool
}

func (v NullableMutableDirectBankTransfer) Get() *MutableDirectBankTransfer {
	return v.value
}

func (v *NullableMutableDirectBankTransfer) Set(val *MutableDirectBankTransfer) {
	v.value = val
	v.isSet = true
}

func (v NullableMutableDirectBankTransfer) IsSet() bool {
	return v.isSet
}

func (v *NullableMutableDirectBankTransfer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMutableDirectBankTransfer(val *MutableDirectBankTransfer) *NullableMutableDirectBankTransfer {
	return &NullableMutableDirectBankTransfer{value: val, isSet: true}
}

func (v NullableMutableDirectBankTransfer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMutableDirectBankTransfer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


