/*
Payment Method Service v2

This API is used for Payment Method Service v2

API version: 2.79.0
*/

// Code generated by OpenAPI Generator; DO NOT EDIT.

package paymentmethod

import (
	"encoding/json"
	
	
	utils "github.com/kennycyb/xendit-go/utils"
	
	"time"
)

// checks if the InternalLATLinked type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &InternalLATLinked{}

// InternalLATLinked struct for InternalLATLinked
type InternalLATLinked struct {
	Event string `json:"event"`
	Timestamp time.Time `json:"timestamp"`
	ChannelCode string `json:"channel_code"`
	Id string `json:"id"`
	Type string `json:"type"`
	Accounts []InternalLATLinkedAccountsInner `json:"accounts"`
}

// NewInternalLATLinked instantiates a new InternalLATLinked object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInternalLATLinked(event string, timestamp time.Time, channelCode string, id string, type_ string, accounts []InternalLATLinkedAccountsInner) *InternalLATLinked {
	this := InternalLATLinked{}
	this.Event = event
	this.Timestamp = timestamp
	this.ChannelCode = channelCode
	this.Id = id
	this.Type = type_
	this.Accounts = accounts
	return &this
}

// NewInternalLATLinkedWithDefaults instantiates a new InternalLATLinked object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInternalLATLinkedWithDefaults() *InternalLATLinked {
	this := InternalLATLinked{}
	return &this
}

// GetEvent returns the Event field value
func (o *InternalLATLinked) GetEvent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *InternalLATLinked) GetEventOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Event, true
}

// SetEvent sets field value
func (o *InternalLATLinked) SetEvent(v string) {
	o.Event = v
}

// GetTimestamp returns the Timestamp field value
func (o *InternalLATLinked) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *InternalLATLinked) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *InternalLATLinked) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

// GetChannelCode returns the ChannelCode field value
func (o *InternalLATLinked) GetChannelCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChannelCode
}

// GetChannelCodeOk returns a tuple with the ChannelCode field value
// and a boolean to check if the value has been set.
func (o *InternalLATLinked) GetChannelCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelCode, true
}

// SetChannelCode sets field value
func (o *InternalLATLinked) SetChannelCode(v string) {
	o.ChannelCode = v
}

// GetId returns the Id field value
func (o *InternalLATLinked) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *InternalLATLinked) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *InternalLATLinked) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *InternalLATLinked) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *InternalLATLinked) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *InternalLATLinked) SetType(v string) {
	o.Type = v
}

// GetAccounts returns the Accounts field value
func (o *InternalLATLinked) GetAccounts() []InternalLATLinkedAccountsInner {
	if o == nil {
		var ret []InternalLATLinkedAccountsInner
		return ret
	}

	return o.Accounts
}

// GetAccountsOk returns a tuple with the Accounts field value
// and a boolean to check if the value has been set.
func (o *InternalLATLinked) GetAccountsOk() ([]InternalLATLinkedAccountsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Accounts, true
}

// SetAccounts sets field value
func (o *InternalLATLinked) SetAccounts(v []InternalLATLinkedAccountsInner) {
	o.Accounts = v
}

func (o InternalLATLinked) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InternalLATLinked) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event"] = o.Event
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["channel_code"] = o.ChannelCode
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["accounts"] = o.Accounts
	return toSerialize, nil
}

type NullableInternalLATLinked struct {
	value *InternalLATLinked
	isSet bool
}

func (v NullableInternalLATLinked) Get() *InternalLATLinked {
	return v.value
}

func (v *NullableInternalLATLinked) Set(val *InternalLATLinked) {
	v.value = val
	v.isSet = true
}

func (v NullableInternalLATLinked) IsSet() bool {
	return v.isSet
}

func (v *NullableInternalLATLinked) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInternalLATLinked(val *InternalLATLinked) *NullableInternalLATLinked {
	return &NullableInternalLATLinked{value: val, isSet: true}
}

func (v NullableInternalLATLinked) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInternalLATLinked) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


