/*
Payment Method Service v2

This API is used for Payment Method Service v2

API version: 2.79.0
*/

// Code generated by OpenAPI Generator; DO NOT EDIT.

package paymentmethod

import (
	"encoding/json"
	
	
	utils "github.com/kennycyb/xendit-go/utils"
	
	"time"
)

// checks if the InternalPaymentMethod type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &InternalPaymentMethod{}

// InternalPaymentMethod struct for InternalPaymentMethod
type InternalPaymentMethod struct {
	Id string `json:"id"`
	BusinessId *string `json:"business_id,omitempty"`
	Type *PaymentMethodType `json:"type,omitempty"`
	Country *PaymentMethodCountry `json:"country,omitempty"`
	CustomerId NullableString `json:"customer_id,omitempty"`
	Customer map[string]interface{} `json:"customer,omitempty"`
	ReferenceId *string `json:"reference_id,omitempty"`
	Description NullableString `json:"description,omitempty"`
	Status *PaymentMethodStatus `json:"status,omitempty"`
	Reusability *PaymentMethodReusability `json:"reusability,omitempty"`
	Actions []PaymentMethodAction `json:"actions,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	BillingInformation NullableBillingInformation `json:"billing_information,omitempty"`
	FailureCode NullableString `json:"failure_code,omitempty"`
	Created *time.Time `json:"created,omitempty"`
	Updated *time.Time `json:"updated,omitempty"`
	Ewallet NullableInternalEwallet `json:"ewallet,omitempty"`
	Card NullableInternalCard `json:"card,omitempty"`
	Cryptocurrency NullableInternalCrypto `json:"cryptocurrency,omitempty"`
	DirectBankTransfer NullableInternalDirectBankTransfer `json:"direct_bank_transfer,omitempty"`
	DirectDebit NullableInternalDirectDebit `json:"direct_debit,omitempty"`
	OverTheCounter NullableInternalOverTheCounter `json:"over_the_counter,omitempty"`
	VirtualAccount NullableInternalVirtualAccount `json:"virtual_account,omitempty"`
	QrCode NullableInternalQRCode `json:"qr_code,omitempty"`
	XCallbackUrl NullableString `json:"x-callback-url,omitempty"`
	ClientType NullableString `json:"client_type,omitempty"`
	InternalMetadata map[string]interface{} `json:"internal_metadata,omitempty"`
}

// NewInternalPaymentMethod instantiates a new InternalPaymentMethod object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInternalPaymentMethod(id string) *InternalPaymentMethod {
	this := InternalPaymentMethod{}
	this.Id = id
	return &this
}

// NewInternalPaymentMethodWithDefaults instantiates a new InternalPaymentMethod object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInternalPaymentMethodWithDefaults() *InternalPaymentMethod {
	this := InternalPaymentMethod{}
	return &this
}

// GetId returns the Id field value
func (o *InternalPaymentMethod) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *InternalPaymentMethod) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *InternalPaymentMethod) SetId(v string) {
	o.Id = v
}

// GetBusinessId returns the BusinessId field value if set, zero value otherwise.
func (o *InternalPaymentMethod) GetBusinessId() string {
	if o == nil || utils.IsNil(o.BusinessId) {
		var ret string
		return ret
	}
	return *o.BusinessId
}

// GetBusinessIdOk returns a tuple with the BusinessId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalPaymentMethod) GetBusinessIdOk() (*string, bool) {
	if o == nil || utils.IsNil(o.BusinessId) {
		return nil, false
	}
	return o.BusinessId, true
}

// HasBusinessId returns a boolean if a field has been set.
func (o *InternalPaymentMethod) HasBusinessId() bool {
	if o != nil && !utils.IsNil(o.BusinessId) {
		return true
	}

	return false
}

// SetBusinessId gets a reference to the given string and assigns it to the BusinessId field.
func (o *InternalPaymentMethod) SetBusinessId(v string) {
	o.BusinessId = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *InternalPaymentMethod) GetType() PaymentMethodType {
	if o == nil || utils.IsNil(o.Type) {
		var ret PaymentMethodType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalPaymentMethod) GetTypeOk() (*PaymentMethodType, bool) {
	if o == nil || utils.IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *InternalPaymentMethod) HasType() bool {
	if o != nil && !utils.IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given PaymentMethodType and assigns it to the Type field.
func (o *InternalPaymentMethod) SetType(v PaymentMethodType) {
	o.Type = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *InternalPaymentMethod) GetCountry() PaymentMethodCountry {
	if o == nil || utils.IsNil(o.Country) {
		var ret PaymentMethodCountry
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalPaymentMethod) GetCountryOk() (*PaymentMethodCountry, bool) {
	if o == nil || utils.IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *InternalPaymentMethod) HasCountry() bool {
	if o != nil && !utils.IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given PaymentMethodCountry and assigns it to the Country field.
func (o *InternalPaymentMethod) SetCountry(v PaymentMethodCountry) {
	o.Country = &v
}

// GetCustomerId returns the CustomerId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InternalPaymentMethod) GetCustomerId() string {
	if o == nil || utils.IsNil(o.CustomerId.Get()) {
		var ret string
		return ret
	}
	return *o.CustomerId.Get()
}

// GetCustomerIdOk returns a tuple with the CustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InternalPaymentMethod) GetCustomerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomerId.Get(), o.CustomerId.IsSet()
}

// HasCustomerId returns a boolean if a field has been set.
func (o *InternalPaymentMethod) HasCustomerId() bool {
	if o != nil && o.CustomerId.IsSet() {
		return true
	}

	return false
}

// SetCustomerId gets a reference to the given NullableString and assigns it to the CustomerId field.
func (o *InternalPaymentMethod) SetCustomerId(v string) {
	o.CustomerId.Set(&v)
}
// SetCustomerIdNil sets the value for CustomerId to be an explicit nil
func (o *InternalPaymentMethod) SetCustomerIdNil() {
	o.CustomerId.Set(nil)
}

// UnsetCustomerId ensures that no value is present for CustomerId, not even an explicit nil
func (o *InternalPaymentMethod) UnsetCustomerId() {
	o.CustomerId.Unset()
}

// GetCustomer returns the Customer field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InternalPaymentMethod) GetCustomer() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Customer
}

// GetCustomerOk returns a tuple with the Customer field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InternalPaymentMethod) GetCustomerOk() (map[string]interface{}, bool) {
	if o == nil || utils.IsNil(o.Customer) {
		return map[string]interface{}{}, false
	}
	return o.Customer, true
}

// HasCustomer returns a boolean if a field has been set.
func (o *InternalPaymentMethod) HasCustomer() bool {
	if o != nil && utils.IsNil(o.Customer) {
		return true
	}

	return false
}

// SetCustomer gets a reference to the given map[string]interface{} and assigns it to the Customer field.
func (o *InternalPaymentMethod) SetCustomer(v map[string]interface{}) {
	o.Customer = v
}

// GetReferenceId returns the ReferenceId field value if set, zero value otherwise.
func (o *InternalPaymentMethod) GetReferenceId() string {
	if o == nil || utils.IsNil(o.ReferenceId) {
		var ret string
		return ret
	}
	return *o.ReferenceId
}

// GetReferenceIdOk returns a tuple with the ReferenceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalPaymentMethod) GetReferenceIdOk() (*string, bool) {
	if o == nil || utils.IsNil(o.ReferenceId) {
		return nil, false
	}
	return o.ReferenceId, true
}

// HasReferenceId returns a boolean if a field has been set.
func (o *InternalPaymentMethod) HasReferenceId() bool {
	if o != nil && !utils.IsNil(o.ReferenceId) {
		return true
	}

	return false
}

// SetReferenceId gets a reference to the given string and assigns it to the ReferenceId field.
func (o *InternalPaymentMethod) SetReferenceId(v string) {
	o.ReferenceId = &v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InternalPaymentMethod) GetDescription() string {
	if o == nil || utils.IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InternalPaymentMethod) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *InternalPaymentMethod) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *InternalPaymentMethod) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *InternalPaymentMethod) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *InternalPaymentMethod) UnsetDescription() {
	o.Description.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *InternalPaymentMethod) GetStatus() PaymentMethodStatus {
	if o == nil || utils.IsNil(o.Status) {
		var ret PaymentMethodStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalPaymentMethod) GetStatusOk() (*PaymentMethodStatus, bool) {
	if o == nil || utils.IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *InternalPaymentMethod) HasStatus() bool {
	if o != nil && !utils.IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given PaymentMethodStatus and assigns it to the Status field.
func (o *InternalPaymentMethod) SetStatus(v PaymentMethodStatus) {
	o.Status = &v
}

// GetReusability returns the Reusability field value if set, zero value otherwise.
func (o *InternalPaymentMethod) GetReusability() PaymentMethodReusability {
	if o == nil || utils.IsNil(o.Reusability) {
		var ret PaymentMethodReusability
		return ret
	}
	return *o.Reusability
}

// GetReusabilityOk returns a tuple with the Reusability field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalPaymentMethod) GetReusabilityOk() (*PaymentMethodReusability, bool) {
	if o == nil || utils.IsNil(o.Reusability) {
		return nil, false
	}
	return o.Reusability, true
}

// HasReusability returns a boolean if a field has been set.
func (o *InternalPaymentMethod) HasReusability() bool {
	if o != nil && !utils.IsNil(o.Reusability) {
		return true
	}

	return false
}

// SetReusability gets a reference to the given PaymentMethodReusability and assigns it to the Reusability field.
func (o *InternalPaymentMethod) SetReusability(v PaymentMethodReusability) {
	o.Reusability = &v
}

// GetActions returns the Actions field value if set, zero value otherwise.
func (o *InternalPaymentMethod) GetActions() []PaymentMethodAction {
	if o == nil || utils.IsNil(o.Actions) {
		var ret []PaymentMethodAction
		return ret
	}
	return o.Actions
}

// GetActionsOk returns a tuple with the Actions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalPaymentMethod) GetActionsOk() ([]PaymentMethodAction, bool) {
	if o == nil || utils.IsNil(o.Actions) {
		return nil, false
	}
	return o.Actions, true
}

// HasActions returns a boolean if a field has been set.
func (o *InternalPaymentMethod) HasActions() bool {
	if o != nil && !utils.IsNil(o.Actions) {
		return true
	}

	return false
}

// SetActions gets a reference to the given []PaymentMethodAction and assigns it to the Actions field.
func (o *InternalPaymentMethod) SetActions(v []PaymentMethodAction) {
	o.Actions = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InternalPaymentMethod) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InternalPaymentMethod) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || utils.IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *InternalPaymentMethod) HasMetadata() bool {
	if o != nil && utils.IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *InternalPaymentMethod) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetBillingInformation returns the BillingInformation field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InternalPaymentMethod) GetBillingInformation() BillingInformation {
	if o == nil || utils.IsNil(o.BillingInformation.Get()) {
		var ret BillingInformation
		return ret
	}
	return *o.BillingInformation.Get()
}

// GetBillingInformationOk returns a tuple with the BillingInformation field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InternalPaymentMethod) GetBillingInformationOk() (*BillingInformation, bool) {
	if o == nil {
		return nil, false
	}
	return o.BillingInformation.Get(), o.BillingInformation.IsSet()
}

// HasBillingInformation returns a boolean if a field has been set.
func (o *InternalPaymentMethod) HasBillingInformation() bool {
	if o != nil && o.BillingInformation.IsSet() {
		return true
	}

	return false
}

// SetBillingInformation gets a reference to the given NullableBillingInformation and assigns it to the BillingInformation field.
func (o *InternalPaymentMethod) SetBillingInformation(v BillingInformation) {
	o.BillingInformation.Set(&v)
}
// SetBillingInformationNil sets the value for BillingInformation to be an explicit nil
func (o *InternalPaymentMethod) SetBillingInformationNil() {
	o.BillingInformation.Set(nil)
}

// UnsetBillingInformation ensures that no value is present for BillingInformation, not even an explicit nil
func (o *InternalPaymentMethod) UnsetBillingInformation() {
	o.BillingInformation.Unset()
}

// GetFailureCode returns the FailureCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InternalPaymentMethod) GetFailureCode() string {
	if o == nil || utils.IsNil(o.FailureCode.Get()) {
		var ret string
		return ret
	}
	return *o.FailureCode.Get()
}

// GetFailureCodeOk returns a tuple with the FailureCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InternalPaymentMethod) GetFailureCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FailureCode.Get(), o.FailureCode.IsSet()
}

// HasFailureCode returns a boolean if a field has been set.
func (o *InternalPaymentMethod) HasFailureCode() bool {
	if o != nil && o.FailureCode.IsSet() {
		return true
	}

	return false
}

// SetFailureCode gets a reference to the given NullableString and assigns it to the FailureCode field.
func (o *InternalPaymentMethod) SetFailureCode(v string) {
	o.FailureCode.Set(&v)
}
// SetFailureCodeNil sets the value for FailureCode to be an explicit nil
func (o *InternalPaymentMethod) SetFailureCodeNil() {
	o.FailureCode.Set(nil)
}

// UnsetFailureCode ensures that no value is present for FailureCode, not even an explicit nil
func (o *InternalPaymentMethod) UnsetFailureCode() {
	o.FailureCode.Unset()
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *InternalPaymentMethod) GetCreated() time.Time {
	if o == nil || utils.IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalPaymentMethod) GetCreatedOk() (*time.Time, bool) {
	if o == nil || utils.IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *InternalPaymentMethod) HasCreated() bool {
	if o != nil && !utils.IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *InternalPaymentMethod) SetCreated(v time.Time) {
	o.Created = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *InternalPaymentMethod) GetUpdated() time.Time {
	if o == nil || utils.IsNil(o.Updated) {
		var ret time.Time
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalPaymentMethod) GetUpdatedOk() (*time.Time, bool) {
	if o == nil || utils.IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *InternalPaymentMethod) HasUpdated() bool {
	if o != nil && !utils.IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given time.Time and assigns it to the Updated field.
func (o *InternalPaymentMethod) SetUpdated(v time.Time) {
	o.Updated = &v
}

// GetEwallet returns the Ewallet field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InternalPaymentMethod) GetEwallet() InternalEwallet {
	if o == nil || utils.IsNil(o.Ewallet.Get()) {
		var ret InternalEwallet
		return ret
	}
	return *o.Ewallet.Get()
}

// GetEwalletOk returns a tuple with the Ewallet field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InternalPaymentMethod) GetEwalletOk() (*InternalEwallet, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ewallet.Get(), o.Ewallet.IsSet()
}

// HasEwallet returns a boolean if a field has been set.
func (o *InternalPaymentMethod) HasEwallet() bool {
	if o != nil && o.Ewallet.IsSet() {
		return true
	}

	return false
}

// SetEwallet gets a reference to the given NullableInternalEwallet and assigns it to the Ewallet field.
func (o *InternalPaymentMethod) SetEwallet(v InternalEwallet) {
	o.Ewallet.Set(&v)
}
// SetEwalletNil sets the value for Ewallet to be an explicit nil
func (o *InternalPaymentMethod) SetEwalletNil() {
	o.Ewallet.Set(nil)
}

// UnsetEwallet ensures that no value is present for Ewallet, not even an explicit nil
func (o *InternalPaymentMethod) UnsetEwallet() {
	o.Ewallet.Unset()
}

// GetCard returns the Card field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InternalPaymentMethod) GetCard() InternalCard {
	if o == nil || utils.IsNil(o.Card.Get()) {
		var ret InternalCard
		return ret
	}
	return *o.Card.Get()
}

// GetCardOk returns a tuple with the Card field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InternalPaymentMethod) GetCardOk() (*InternalCard, bool) {
	if o == nil {
		return nil, false
	}
	return o.Card.Get(), o.Card.IsSet()
}

// HasCard returns a boolean if a field has been set.
func (o *InternalPaymentMethod) HasCard() bool {
	if o != nil && o.Card.IsSet() {
		return true
	}

	return false
}

// SetCard gets a reference to the given NullableInternalCard and assigns it to the Card field.
func (o *InternalPaymentMethod) SetCard(v InternalCard) {
	o.Card.Set(&v)
}
// SetCardNil sets the value for Card to be an explicit nil
func (o *InternalPaymentMethod) SetCardNil() {
	o.Card.Set(nil)
}

// UnsetCard ensures that no value is present for Card, not even an explicit nil
func (o *InternalPaymentMethod) UnsetCard() {
	o.Card.Unset()
}

// GetCryptocurrency returns the Cryptocurrency field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InternalPaymentMethod) GetCryptocurrency() InternalCrypto {
	if o == nil || utils.IsNil(o.Cryptocurrency.Get()) {
		var ret InternalCrypto
		return ret
	}
	return *o.Cryptocurrency.Get()
}

// GetCryptocurrencyOk returns a tuple with the Cryptocurrency field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InternalPaymentMethod) GetCryptocurrencyOk() (*InternalCrypto, bool) {
	if o == nil {
		return nil, false
	}
	return o.Cryptocurrency.Get(), o.Cryptocurrency.IsSet()
}

// HasCryptocurrency returns a boolean if a field has been set.
func (o *InternalPaymentMethod) HasCryptocurrency() bool {
	if o != nil && o.Cryptocurrency.IsSet() {
		return true
	}

	return false
}

// SetCryptocurrency gets a reference to the given NullableInternalCrypto and assigns it to the Cryptocurrency field.
func (o *InternalPaymentMethod) SetCryptocurrency(v InternalCrypto) {
	o.Cryptocurrency.Set(&v)
}
// SetCryptocurrencyNil sets the value for Cryptocurrency to be an explicit nil
func (o *InternalPaymentMethod) SetCryptocurrencyNil() {
	o.Cryptocurrency.Set(nil)
}

// UnsetCryptocurrency ensures that no value is present for Cryptocurrency, not even an explicit nil
func (o *InternalPaymentMethod) UnsetCryptocurrency() {
	o.Cryptocurrency.Unset()
}

// GetDirectBankTransfer returns the DirectBankTransfer field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InternalPaymentMethod) GetDirectBankTransfer() InternalDirectBankTransfer {
	if o == nil || utils.IsNil(o.DirectBankTransfer.Get()) {
		var ret InternalDirectBankTransfer
		return ret
	}
	return *o.DirectBankTransfer.Get()
}

// GetDirectBankTransferOk returns a tuple with the DirectBankTransfer field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InternalPaymentMethod) GetDirectBankTransferOk() (*InternalDirectBankTransfer, bool) {
	if o == nil {
		return nil, false
	}
	return o.DirectBankTransfer.Get(), o.DirectBankTransfer.IsSet()
}

// HasDirectBankTransfer returns a boolean if a field has been set.
func (o *InternalPaymentMethod) HasDirectBankTransfer() bool {
	if o != nil && o.DirectBankTransfer.IsSet() {
		return true
	}

	return false
}

// SetDirectBankTransfer gets a reference to the given NullableInternalDirectBankTransfer and assigns it to the DirectBankTransfer field.
func (o *InternalPaymentMethod) SetDirectBankTransfer(v InternalDirectBankTransfer) {
	o.DirectBankTransfer.Set(&v)
}
// SetDirectBankTransferNil sets the value for DirectBankTransfer to be an explicit nil
func (o *InternalPaymentMethod) SetDirectBankTransferNil() {
	o.DirectBankTransfer.Set(nil)
}

// UnsetDirectBankTransfer ensures that no value is present for DirectBankTransfer, not even an explicit nil
func (o *InternalPaymentMethod) UnsetDirectBankTransfer() {
	o.DirectBankTransfer.Unset()
}

// GetDirectDebit returns the DirectDebit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InternalPaymentMethod) GetDirectDebit() InternalDirectDebit {
	if o == nil || utils.IsNil(o.DirectDebit.Get()) {
		var ret InternalDirectDebit
		return ret
	}
	return *o.DirectDebit.Get()
}

// GetDirectDebitOk returns a tuple with the DirectDebit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InternalPaymentMethod) GetDirectDebitOk() (*InternalDirectDebit, bool) {
	if o == nil {
		return nil, false
	}
	return o.DirectDebit.Get(), o.DirectDebit.IsSet()
}

// HasDirectDebit returns a boolean if a field has been set.
func (o *InternalPaymentMethod) HasDirectDebit() bool {
	if o != nil && o.DirectDebit.IsSet() {
		return true
	}

	return false
}

// SetDirectDebit gets a reference to the given NullableInternalDirectDebit and assigns it to the DirectDebit field.
func (o *InternalPaymentMethod) SetDirectDebit(v InternalDirectDebit) {
	o.DirectDebit.Set(&v)
}
// SetDirectDebitNil sets the value for DirectDebit to be an explicit nil
func (o *InternalPaymentMethod) SetDirectDebitNil() {
	o.DirectDebit.Set(nil)
}

// UnsetDirectDebit ensures that no value is present for DirectDebit, not even an explicit nil
func (o *InternalPaymentMethod) UnsetDirectDebit() {
	o.DirectDebit.Unset()
}

// GetOverTheCounter returns the OverTheCounter field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InternalPaymentMethod) GetOverTheCounter() InternalOverTheCounter {
	if o == nil || utils.IsNil(o.OverTheCounter.Get()) {
		var ret InternalOverTheCounter
		return ret
	}
	return *o.OverTheCounter.Get()
}

// GetOverTheCounterOk returns a tuple with the OverTheCounter field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InternalPaymentMethod) GetOverTheCounterOk() (*InternalOverTheCounter, bool) {
	if o == nil {
		return nil, false
	}
	return o.OverTheCounter.Get(), o.OverTheCounter.IsSet()
}

// HasOverTheCounter returns a boolean if a field has been set.
func (o *InternalPaymentMethod) HasOverTheCounter() bool {
	if o != nil && o.OverTheCounter.IsSet() {
		return true
	}

	return false
}

// SetOverTheCounter gets a reference to the given NullableInternalOverTheCounter and assigns it to the OverTheCounter field.
func (o *InternalPaymentMethod) SetOverTheCounter(v InternalOverTheCounter) {
	o.OverTheCounter.Set(&v)
}
// SetOverTheCounterNil sets the value for OverTheCounter to be an explicit nil
func (o *InternalPaymentMethod) SetOverTheCounterNil() {
	o.OverTheCounter.Set(nil)
}

// UnsetOverTheCounter ensures that no value is present for OverTheCounter, not even an explicit nil
func (o *InternalPaymentMethod) UnsetOverTheCounter() {
	o.OverTheCounter.Unset()
}

// GetVirtualAccount returns the VirtualAccount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InternalPaymentMethod) GetVirtualAccount() InternalVirtualAccount {
	if o == nil || utils.IsNil(o.VirtualAccount.Get()) {
		var ret InternalVirtualAccount
		return ret
	}
	return *o.VirtualAccount.Get()
}

// GetVirtualAccountOk returns a tuple with the VirtualAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InternalPaymentMethod) GetVirtualAccountOk() (*InternalVirtualAccount, bool) {
	if o == nil {
		return nil, false
	}
	return o.VirtualAccount.Get(), o.VirtualAccount.IsSet()
}

// HasVirtualAccount returns a boolean if a field has been set.
func (o *InternalPaymentMethod) HasVirtualAccount() bool {
	if o != nil && o.VirtualAccount.IsSet() {
		return true
	}

	return false
}

// SetVirtualAccount gets a reference to the given NullableInternalVirtualAccount and assigns it to the VirtualAccount field.
func (o *InternalPaymentMethod) SetVirtualAccount(v InternalVirtualAccount) {
	o.VirtualAccount.Set(&v)
}
// SetVirtualAccountNil sets the value for VirtualAccount to be an explicit nil
func (o *InternalPaymentMethod) SetVirtualAccountNil() {
	o.VirtualAccount.Set(nil)
}

// UnsetVirtualAccount ensures that no value is present for VirtualAccount, not even an explicit nil
func (o *InternalPaymentMethod) UnsetVirtualAccount() {
	o.VirtualAccount.Unset()
}

// GetQrCode returns the QrCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InternalPaymentMethod) GetQrCode() InternalQRCode {
	if o == nil || utils.IsNil(o.QrCode.Get()) {
		var ret InternalQRCode
		return ret
	}
	return *o.QrCode.Get()
}

// GetQrCodeOk returns a tuple with the QrCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InternalPaymentMethod) GetQrCodeOk() (*InternalQRCode, bool) {
	if o == nil {
		return nil, false
	}
	return o.QrCode.Get(), o.QrCode.IsSet()
}

// HasQrCode returns a boolean if a field has been set.
func (o *InternalPaymentMethod) HasQrCode() bool {
	if o != nil && o.QrCode.IsSet() {
		return true
	}

	return false
}

// SetQrCode gets a reference to the given NullableInternalQRCode and assigns it to the QrCode field.
func (o *InternalPaymentMethod) SetQrCode(v InternalQRCode) {
	o.QrCode.Set(&v)
}
// SetQrCodeNil sets the value for QrCode to be an explicit nil
func (o *InternalPaymentMethod) SetQrCodeNil() {
	o.QrCode.Set(nil)
}

// UnsetQrCode ensures that no value is present for QrCode, not even an explicit nil
func (o *InternalPaymentMethod) UnsetQrCode() {
	o.QrCode.Unset()
}

// GetXCallbackUrl returns the XCallbackUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InternalPaymentMethod) GetXCallbackUrl() string {
	if o == nil || utils.IsNil(o.XCallbackUrl.Get()) {
		var ret string
		return ret
	}
	return *o.XCallbackUrl.Get()
}

// GetXCallbackUrlOk returns a tuple with the XCallbackUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InternalPaymentMethod) GetXCallbackUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.XCallbackUrl.Get(), o.XCallbackUrl.IsSet()
}

// HasXCallbackUrl returns a boolean if a field has been set.
func (o *InternalPaymentMethod) HasXCallbackUrl() bool {
	if o != nil && o.XCallbackUrl.IsSet() {
		return true
	}

	return false
}

// SetXCallbackUrl gets a reference to the given NullableString and assigns it to the XCallbackUrl field.
func (o *InternalPaymentMethod) SetXCallbackUrl(v string) {
	o.XCallbackUrl.Set(&v)
}
// SetXCallbackUrlNil sets the value for XCallbackUrl to be an explicit nil
func (o *InternalPaymentMethod) SetXCallbackUrlNil() {
	o.XCallbackUrl.Set(nil)
}

// UnsetXCallbackUrl ensures that no value is present for XCallbackUrl, not even an explicit nil
func (o *InternalPaymentMethod) UnsetXCallbackUrl() {
	o.XCallbackUrl.Unset()
}

// GetClientType returns the ClientType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InternalPaymentMethod) GetClientType() string {
	if o == nil || utils.IsNil(o.ClientType.Get()) {
		var ret string
		return ret
	}
	return *o.ClientType.Get()
}

// GetClientTypeOk returns a tuple with the ClientType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InternalPaymentMethod) GetClientTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ClientType.Get(), o.ClientType.IsSet()
}

// HasClientType returns a boolean if a field has been set.
func (o *InternalPaymentMethod) HasClientType() bool {
	if o != nil && o.ClientType.IsSet() {
		return true
	}

	return false
}

// SetClientType gets a reference to the given NullableString and assigns it to the ClientType field.
func (o *InternalPaymentMethod) SetClientType(v string) {
	o.ClientType.Set(&v)
}
// SetClientTypeNil sets the value for ClientType to be an explicit nil
func (o *InternalPaymentMethod) SetClientTypeNil() {
	o.ClientType.Set(nil)
}

// UnsetClientType ensures that no value is present for ClientType, not even an explicit nil
func (o *InternalPaymentMethod) UnsetClientType() {
	o.ClientType.Unset()
}

// GetInternalMetadata returns the InternalMetadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InternalPaymentMethod) GetInternalMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.InternalMetadata
}

// GetInternalMetadataOk returns a tuple with the InternalMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InternalPaymentMethod) GetInternalMetadataOk() (map[string]interface{}, bool) {
	if o == nil || utils.IsNil(o.InternalMetadata) {
		return map[string]interface{}{}, false
	}
	return o.InternalMetadata, true
}

// HasInternalMetadata returns a boolean if a field has been set.
func (o *InternalPaymentMethod) HasInternalMetadata() bool {
	if o != nil && utils.IsNil(o.InternalMetadata) {
		return true
	}

	return false
}

// SetInternalMetadata gets a reference to the given map[string]interface{} and assigns it to the InternalMetadata field.
func (o *InternalPaymentMethod) SetInternalMetadata(v map[string]interface{}) {
	o.InternalMetadata = v
}

func (o InternalPaymentMethod) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InternalPaymentMethod) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !utils.IsNil(o.BusinessId) {
		toSerialize["business_id"] = o.BusinessId
	}
	if !utils.IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !utils.IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if o.CustomerId.IsSet() {
		toSerialize["customer_id"] = o.CustomerId.Get()
	}
	if o.Customer != nil {
		toSerialize["customer"] = o.Customer
	}
	if !utils.IsNil(o.ReferenceId) {
		toSerialize["reference_id"] = o.ReferenceId
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !utils.IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !utils.IsNil(o.Reusability) {
		toSerialize["reusability"] = o.Reusability
	}
	if !utils.IsNil(o.Actions) {
		toSerialize["actions"] = o.Actions
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if o.BillingInformation.IsSet() {
		toSerialize["billing_information"] = o.BillingInformation.Get()
	}
	if o.FailureCode.IsSet() {
		toSerialize["failure_code"] = o.FailureCode.Get()
	}
	if !utils.IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !utils.IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	if o.Ewallet.IsSet() {
		toSerialize["ewallet"] = o.Ewallet.Get()
	}
	if o.Card.IsSet() {
		toSerialize["card"] = o.Card.Get()
	}
	if o.Cryptocurrency.IsSet() {
		toSerialize["cryptocurrency"] = o.Cryptocurrency.Get()
	}
	if o.DirectBankTransfer.IsSet() {
		toSerialize["direct_bank_transfer"] = o.DirectBankTransfer.Get()
	}
	if o.DirectDebit.IsSet() {
		toSerialize["direct_debit"] = o.DirectDebit.Get()
	}
	if o.OverTheCounter.IsSet() {
		toSerialize["over_the_counter"] = o.OverTheCounter.Get()
	}
	if o.VirtualAccount.IsSet() {
		toSerialize["virtual_account"] = o.VirtualAccount.Get()
	}
	if o.QrCode.IsSet() {
		toSerialize["qr_code"] = o.QrCode.Get()
	}
	if o.XCallbackUrl.IsSet() {
		toSerialize["x-callback-url"] = o.XCallbackUrl.Get()
	}
	if o.ClientType.IsSet() {
		toSerialize["client_type"] = o.ClientType.Get()
	}
	if o.InternalMetadata != nil {
		toSerialize["internal_metadata"] = o.InternalMetadata
	}
	return toSerialize, nil
}

type NullableInternalPaymentMethod struct {
	value *InternalPaymentMethod
	isSet bool
}

func (v NullableInternalPaymentMethod) Get() *InternalPaymentMethod {
	return v.value
}

func (v *NullableInternalPaymentMethod) Set(val *InternalPaymentMethod) {
	v.value = val
	v.isSet = true
}

func (v NullableInternalPaymentMethod) IsSet() bool {
	return v.isSet
}

func (v *NullableInternalPaymentMethod) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInternalPaymentMethod(val *InternalPaymentMethod) *NullableInternalPaymentMethod {
	return &NullableInternalPaymentMethod{value: val, isSet: true}
}

func (v NullableInternalPaymentMethod) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInternalPaymentMethod) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


