/*
Payment Method Service v2

This API is used for Payment Method Service v2

API version: 2.79.0
*/

// Code generated by OpenAPI Generator; DO NOT EDIT.

package paymentmethod

import (
	"encoding/json"
	
	
	utils "github.com/kennycyb/xendit-go/utils"
	
)

// checks if the MutableDirectDebit type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &MutableDirectDebit{}

// MutableDirectDebit struct for MutableDirectDebit
type MutableDirectDebit struct {
	ChannelCode DirectDebitChannelCode `json:"channel_code"`
	ChannelProperties NullableDirectDebitChannelProperties `json:"channel_properties"`
}

// NewMutableDirectDebit instantiates a new MutableDirectDebit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMutableDirectDebit(channelCode DirectDebitChannelCode, channelProperties NullableDirectDebitChannelProperties) *MutableDirectDebit {
	this := MutableDirectDebit{}
	this.ChannelCode = channelCode
	this.ChannelProperties = channelProperties
	return &this
}

// NewMutableDirectDebitWithDefaults instantiates a new MutableDirectDebit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMutableDirectDebitWithDefaults() *MutableDirectDebit {
	this := MutableDirectDebit{}
	return &this
}

// GetChannelCode returns the ChannelCode field value
func (o *MutableDirectDebit) GetChannelCode() DirectDebitChannelCode {
	if o == nil {
		var ret DirectDebitChannelCode
		return ret
	}

	return o.ChannelCode
}

// GetChannelCodeOk returns a tuple with the ChannelCode field value
// and a boolean to check if the value has been set.
func (o *MutableDirectDebit) GetChannelCodeOk() (*DirectDebitChannelCode, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelCode, true
}

// SetChannelCode sets field value
func (o *MutableDirectDebit) SetChannelCode(v DirectDebitChannelCode) {
	o.ChannelCode = v
}

// GetChannelProperties returns the ChannelProperties field value
// If the value is explicit nil, the zero value for DirectDebitChannelProperties will be returned
func (o *MutableDirectDebit) GetChannelProperties() DirectDebitChannelProperties {
	if o == nil || o.ChannelProperties.Get() == nil {
		var ret DirectDebitChannelProperties
		return ret
	}

	return *o.ChannelProperties.Get()
}

// GetChannelPropertiesOk returns a tuple with the ChannelProperties field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MutableDirectDebit) GetChannelPropertiesOk() (*DirectDebitChannelProperties, bool) {
	if o == nil {
		return nil, false
	}
	return o.ChannelProperties.Get(), o.ChannelProperties.IsSet()
}

// SetChannelProperties sets field value
func (o *MutableDirectDebit) SetChannelProperties(v DirectDebitChannelProperties) {
	o.ChannelProperties.Set(&v)
}

func (o MutableDirectDebit) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MutableDirectDebit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["channel_code"] = o.ChannelCode
	toSerialize["channel_properties"] = o.ChannelProperties.Get()
	return toSerialize, nil
}

type NullableMutableDirectDebit struct {
	value *MutableDirectDebit
	isSet bool
}

func (v NullableMutableDirectDebit) Get() *MutableDirectDebit {
	return v.value
}

func (v *NullableMutableDirectDebit) Set(val *MutableDirectDebit) {
	v.value = val
	v.isSet = true
}

func (v NullableMutableDirectDebit) IsSet() bool {
	return v.isSet
}

func (v *NullableMutableDirectDebit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMutableDirectDebit(val *MutableDirectDebit) *NullableMutableDirectDebit {
	return &NullableMutableDirectDebit{value: val, isSet: true}
}

func (v NullableMutableDirectDebit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMutableDirectDebit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


