/*
Payment Method Service v2

This API is used for Payment Method Service v2

API version: 2.79.0
*/

// Code generated by OpenAPI Generator; DO NOT EDIT.

package paymentmethod

import (
	"encoding/json"
	
	
	utils "github.com/kennycyb/xendit-go/utils"
	
)

// checks if the EwalletChannelProperties type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &EwalletChannelProperties{}

// EwalletChannelProperties Ewallet Channel Properties
type EwalletChannelProperties struct {
	// URL where the end-customer is redirected if the authorization is successful
	SuccessReturnUrl *string `json:"success_return_url,omitempty"`
	// URL where the end-customer is redirected if the authorization failed
	FailureReturnUrl *string `json:"failure_return_url,omitempty"`
	// URL where the end-customer is redirected if the authorization cancelled
	CancelReturnUrl *string `json:"cancel_return_url,omitempty"`
	// Mobile number of customer in E.164 format (e.g. +628123123123). For OVO one time payment use only.
	MobileNumber *string `json:"mobile_number,omitempty"`
	// REDEEM_NONE will not use any point, REDEEM_ALL will use all available points before cash balance is used. For OVO and ShopeePay tokenized payment use only.
	RedeemPoints *string `json:"redeem_points,omitempty"`
	// Available for JENIUSPAY only
	Cashtag *string `json:"cashtag,omitempty"`
}

// NewEwalletChannelProperties instantiates a new EwalletChannelProperties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEwalletChannelProperties() *EwalletChannelProperties {
	this := EwalletChannelProperties{}
	return &this
}

// NewEwalletChannelPropertiesWithDefaults instantiates a new EwalletChannelProperties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEwalletChannelPropertiesWithDefaults() *EwalletChannelProperties {
	this := EwalletChannelProperties{}
	return &this
}

// GetSuccessReturnUrl returns the SuccessReturnUrl field value if set, zero value otherwise.
func (o *EwalletChannelProperties) GetSuccessReturnUrl() string {
	if o == nil || utils.IsNil(o.SuccessReturnUrl) {
		var ret string
		return ret
	}
	return *o.SuccessReturnUrl
}

// GetSuccessReturnUrlOk returns a tuple with the SuccessReturnUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EwalletChannelProperties) GetSuccessReturnUrlOk() (*string, bool) {
	if o == nil || utils.IsNil(o.SuccessReturnUrl) {
		return nil, false
	}
	return o.SuccessReturnUrl, true
}

// HasSuccessReturnUrl returns a boolean if a field has been set.
func (o *EwalletChannelProperties) HasSuccessReturnUrl() bool {
	if o != nil && !utils.IsNil(o.SuccessReturnUrl) {
		return true
	}

	return false
}

// SetSuccessReturnUrl gets a reference to the given string and assigns it to the SuccessReturnUrl field.
func (o *EwalletChannelProperties) SetSuccessReturnUrl(v string) {
	o.SuccessReturnUrl = &v
}

// GetFailureReturnUrl returns the FailureReturnUrl field value if set, zero value otherwise.
func (o *EwalletChannelProperties) GetFailureReturnUrl() string {
	if o == nil || utils.IsNil(o.FailureReturnUrl) {
		var ret string
		return ret
	}
	return *o.FailureReturnUrl
}

// GetFailureReturnUrlOk returns a tuple with the FailureReturnUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EwalletChannelProperties) GetFailureReturnUrlOk() (*string, bool) {
	if o == nil || utils.IsNil(o.FailureReturnUrl) {
		return nil, false
	}
	return o.FailureReturnUrl, true
}

// HasFailureReturnUrl returns a boolean if a field has been set.
func (o *EwalletChannelProperties) HasFailureReturnUrl() bool {
	if o != nil && !utils.IsNil(o.FailureReturnUrl) {
		return true
	}

	return false
}

// SetFailureReturnUrl gets a reference to the given string and assigns it to the FailureReturnUrl field.
func (o *EwalletChannelProperties) SetFailureReturnUrl(v string) {
	o.FailureReturnUrl = &v
}

// GetCancelReturnUrl returns the CancelReturnUrl field value if set, zero value otherwise.
func (o *EwalletChannelProperties) GetCancelReturnUrl() string {
	if o == nil || utils.IsNil(o.CancelReturnUrl) {
		var ret string
		return ret
	}
	return *o.CancelReturnUrl
}

// GetCancelReturnUrlOk returns a tuple with the CancelReturnUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EwalletChannelProperties) GetCancelReturnUrlOk() (*string, bool) {
	if o == nil || utils.IsNil(o.CancelReturnUrl) {
		return nil, false
	}
	return o.CancelReturnUrl, true
}

// HasCancelReturnUrl returns a boolean if a field has been set.
func (o *EwalletChannelProperties) HasCancelReturnUrl() bool {
	if o != nil && !utils.IsNil(o.CancelReturnUrl) {
		return true
	}

	return false
}

// SetCancelReturnUrl gets a reference to the given string and assigns it to the CancelReturnUrl field.
func (o *EwalletChannelProperties) SetCancelReturnUrl(v string) {
	o.CancelReturnUrl = &v
}

// GetMobileNumber returns the MobileNumber field value if set, zero value otherwise.
func (o *EwalletChannelProperties) GetMobileNumber() string {
	if o == nil || utils.IsNil(o.MobileNumber) {
		var ret string
		return ret
	}
	return *o.MobileNumber
}

// GetMobileNumberOk returns a tuple with the MobileNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EwalletChannelProperties) GetMobileNumberOk() (*string, bool) {
	if o == nil || utils.IsNil(o.MobileNumber) {
		return nil, false
	}
	return o.MobileNumber, true
}

// HasMobileNumber returns a boolean if a field has been set.
func (o *EwalletChannelProperties) HasMobileNumber() bool {
	if o != nil && !utils.IsNil(o.MobileNumber) {
		return true
	}

	return false
}

// SetMobileNumber gets a reference to the given string and assigns it to the MobileNumber field.
func (o *EwalletChannelProperties) SetMobileNumber(v string) {
	o.MobileNumber = &v
}

// GetRedeemPoints returns the RedeemPoints field value if set, zero value otherwise.
func (o *EwalletChannelProperties) GetRedeemPoints() string {
	if o == nil || utils.IsNil(o.RedeemPoints) {
		var ret string
		return ret
	}
	return *o.RedeemPoints
}

// GetRedeemPointsOk returns a tuple with the RedeemPoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EwalletChannelProperties) GetRedeemPointsOk() (*string, bool) {
	if o == nil || utils.IsNil(o.RedeemPoints) {
		return nil, false
	}
	return o.RedeemPoints, true
}

// HasRedeemPoints returns a boolean if a field has been set.
func (o *EwalletChannelProperties) HasRedeemPoints() bool {
	if o != nil && !utils.IsNil(o.RedeemPoints) {
		return true
	}

	return false
}

// SetRedeemPoints gets a reference to the given string and assigns it to the RedeemPoints field.
func (o *EwalletChannelProperties) SetRedeemPoints(v string) {
	o.RedeemPoints = &v
}

// GetCashtag returns the Cashtag field value if set, zero value otherwise.
func (o *EwalletChannelProperties) GetCashtag() string {
	if o == nil || utils.IsNil(o.Cashtag) {
		var ret string
		return ret
	}
	return *o.Cashtag
}

// GetCashtagOk returns a tuple with the Cashtag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EwalletChannelProperties) GetCashtagOk() (*string, bool) {
	if o == nil || utils.IsNil(o.Cashtag) {
		return nil, false
	}
	return o.Cashtag, true
}

// HasCashtag returns a boolean if a field has been set.
func (o *EwalletChannelProperties) HasCashtag() bool {
	if o != nil && !utils.IsNil(o.Cashtag) {
		return true
	}

	return false
}

// SetCashtag gets a reference to the given string and assigns it to the Cashtag field.
func (o *EwalletChannelProperties) SetCashtag(v string) {
	o.Cashtag = &v
}

func (o EwalletChannelProperties) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EwalletChannelProperties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.SuccessReturnUrl) {
		toSerialize["success_return_url"] = o.SuccessReturnUrl
	}
	if !utils.IsNil(o.FailureReturnUrl) {
		toSerialize["failure_return_url"] = o.FailureReturnUrl
	}
	if !utils.IsNil(o.CancelReturnUrl) {
		toSerialize["cancel_return_url"] = o.CancelReturnUrl
	}
	if !utils.IsNil(o.MobileNumber) {
		toSerialize["mobile_number"] = o.MobileNumber
	}
	if !utils.IsNil(o.RedeemPoints) {
		toSerialize["redeem_points"] = o.RedeemPoints
	}
	if !utils.IsNil(o.Cashtag) {
		toSerialize["cashtag"] = o.Cashtag
	}
	return toSerialize, nil
}

type NullableEwalletChannelProperties struct {
	value *EwalletChannelProperties
	isSet bool
}

func (v NullableEwalletChannelProperties) Get() *EwalletChannelProperties {
	return v.value
}

func (v *NullableEwalletChannelProperties) Set(val *EwalletChannelProperties) {
	v.value = val
	v.isSet = true
}

func (v NullableEwalletChannelProperties) IsSet() bool {
	return v.isSet
}

func (v *NullableEwalletChannelProperties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEwalletChannelProperties(val *EwalletChannelProperties) *NullableEwalletChannelProperties {
	return &NullableEwalletChannelProperties{value: val, isSet: true}
}

func (v NullableEwalletChannelProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEwalletChannelProperties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


