/*
Payment Method Service v2

This API is used for Payment Method Service v2

API version: 2.79.0
*/

// Code generated by OpenAPI Generator; DO NOT EDIT.

package paymentmethod

import (
	"encoding/json"
	
	
	utils "github.com/kennycyb/xendit-go/utils"
	
)

// checks if the PublicSimulatePaymentChannelHealth type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &PublicSimulatePaymentChannelHealth{}

// PublicSimulatePaymentChannelHealth struct for PublicSimulatePaymentChannelHealth
type PublicSimulatePaymentChannelHealth struct {
	// Payment channel health event
	Event *string `json:"event,omitempty"`
	// Business ID registered to payment channel downtime or online callback URL
	BusinessId *string `json:"business_id,omitempty"`
	// Date time the event is triggered
	Created *string `json:"created,omitempty"`
	Data *PublicPaymentChannelDowntimeOnlineData `json:"data,omitempty"`
}

// NewPublicSimulatePaymentChannelHealth instantiates a new PublicSimulatePaymentChannelHealth object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublicSimulatePaymentChannelHealth() *PublicSimulatePaymentChannelHealth {
	this := PublicSimulatePaymentChannelHealth{}
	return &this
}

// NewPublicSimulatePaymentChannelHealthWithDefaults instantiates a new PublicSimulatePaymentChannelHealth object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublicSimulatePaymentChannelHealthWithDefaults() *PublicSimulatePaymentChannelHealth {
	this := PublicSimulatePaymentChannelHealth{}
	return &this
}

// GetEvent returns the Event field value if set, zero value otherwise.
func (o *PublicSimulatePaymentChannelHealth) GetEvent() string {
	if o == nil || utils.IsNil(o.Event) {
		var ret string
		return ret
	}
	return *o.Event
}

// GetEventOk returns a tuple with the Event field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicSimulatePaymentChannelHealth) GetEventOk() (*string, bool) {
	if o == nil || utils.IsNil(o.Event) {
		return nil, false
	}
	return o.Event, true
}

// HasEvent returns a boolean if a field has been set.
func (o *PublicSimulatePaymentChannelHealth) HasEvent() bool {
	if o != nil && !utils.IsNil(o.Event) {
		return true
	}

	return false
}

// SetEvent gets a reference to the given string and assigns it to the Event field.
func (o *PublicSimulatePaymentChannelHealth) SetEvent(v string) {
	o.Event = &v
}

// GetBusinessId returns the BusinessId field value if set, zero value otherwise.
func (o *PublicSimulatePaymentChannelHealth) GetBusinessId() string {
	if o == nil || utils.IsNil(o.BusinessId) {
		var ret string
		return ret
	}
	return *o.BusinessId
}

// GetBusinessIdOk returns a tuple with the BusinessId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicSimulatePaymentChannelHealth) GetBusinessIdOk() (*string, bool) {
	if o == nil || utils.IsNil(o.BusinessId) {
		return nil, false
	}
	return o.BusinessId, true
}

// HasBusinessId returns a boolean if a field has been set.
func (o *PublicSimulatePaymentChannelHealth) HasBusinessId() bool {
	if o != nil && !utils.IsNil(o.BusinessId) {
		return true
	}

	return false
}

// SetBusinessId gets a reference to the given string and assigns it to the BusinessId field.
func (o *PublicSimulatePaymentChannelHealth) SetBusinessId(v string) {
	o.BusinessId = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *PublicSimulatePaymentChannelHealth) GetCreated() string {
	if o == nil || utils.IsNil(o.Created) {
		var ret string
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicSimulatePaymentChannelHealth) GetCreatedOk() (*string, bool) {
	if o == nil || utils.IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *PublicSimulatePaymentChannelHealth) HasCreated() bool {
	if o != nil && !utils.IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given string and assigns it to the Created field.
func (o *PublicSimulatePaymentChannelHealth) SetCreated(v string) {
	o.Created = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *PublicSimulatePaymentChannelHealth) GetData() PublicPaymentChannelDowntimeOnlineData {
	if o == nil || utils.IsNil(o.Data) {
		var ret PublicPaymentChannelDowntimeOnlineData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicSimulatePaymentChannelHealth) GetDataOk() (*PublicPaymentChannelDowntimeOnlineData, bool) {
	if o == nil || utils.IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *PublicSimulatePaymentChannelHealth) HasData() bool {
	if o != nil && !utils.IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given PublicPaymentChannelDowntimeOnlineData and assigns it to the Data field.
func (o *PublicSimulatePaymentChannelHealth) SetData(v PublicPaymentChannelDowntimeOnlineData) {
	o.Data = &v
}

func (o PublicSimulatePaymentChannelHealth) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublicSimulatePaymentChannelHealth) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.Event) {
		toSerialize["event"] = o.Event
	}
	if !utils.IsNil(o.BusinessId) {
		toSerialize["business_id"] = o.BusinessId
	}
	if !utils.IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !utils.IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullablePublicSimulatePaymentChannelHealth struct {
	value *PublicSimulatePaymentChannelHealth
	isSet bool
}

func (v NullablePublicSimulatePaymentChannelHealth) Get() *PublicSimulatePaymentChannelHealth {
	return v.value
}

func (v *NullablePublicSimulatePaymentChannelHealth) Set(val *PublicSimulatePaymentChannelHealth) {
	v.value = val
	v.isSet = true
}

func (v NullablePublicSimulatePaymentChannelHealth) IsSet() bool {
	return v.isSet
}

func (v *NullablePublicSimulatePaymentChannelHealth) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublicSimulatePaymentChannelHealth(val *PublicSimulatePaymentChannelHealth) *NullablePublicSimulatePaymentChannelHealth {
	return &NullablePublicSimulatePaymentChannelHealth{value: val, isSet: true}
}

func (v NullablePublicSimulatePaymentChannelHealth) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublicSimulatePaymentChannelHealth) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


