/*
Payment Method Service v2

This API is used for Payment Method Service v2

API version: 2.79.0
*/

// Code generated by OpenAPI Generator; DO NOT EDIT.

package paymentmethod

import (
	"encoding/json"
	
	
	utils "github.com/kennycyb/xendit-go/utils"
	
)

// checks if the MutableOverTheCounter type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &MutableOverTheCounter{}

// MutableOverTheCounter struct for MutableOverTheCounter
type MutableOverTheCounter struct {
	Amount NullableFloat64 `json:"amount,omitempty"`
	Currency *string `json:"currency,omitempty"`
	ChannelCode OverTheCounterChannelCode `json:"channel_code"`
	ChannelProperties OverTheCounterChannelProperties `json:"channel_properties"`
}

// NewMutableOverTheCounter instantiates a new MutableOverTheCounter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMutableOverTheCounter(channelCode OverTheCounterChannelCode, channelProperties OverTheCounterChannelProperties) *MutableOverTheCounter {
	this := MutableOverTheCounter{}
	this.ChannelCode = channelCode
	this.ChannelProperties = channelProperties
	return &this
}

// NewMutableOverTheCounterWithDefaults instantiates a new MutableOverTheCounter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMutableOverTheCounterWithDefaults() *MutableOverTheCounter {
	this := MutableOverTheCounter{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MutableOverTheCounter) GetAmount() float64 {
	if o == nil || utils.IsNil(o.Amount.Get()) {
		var ret float64
		return ret
	}
	return *o.Amount.Get()
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MutableOverTheCounter) GetAmountOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Amount.Get(), o.Amount.IsSet()
}

// HasAmount returns a boolean if a field has been set.
func (o *MutableOverTheCounter) HasAmount() bool {
	if o != nil && o.Amount.IsSet() {
		return true
	}

	return false
}

// SetAmount gets a reference to the given NullableFloat64 and assigns it to the Amount field.
func (o *MutableOverTheCounter) SetAmount(v float64) {
	o.Amount.Set(&v)
}
// SetAmountNil sets the value for Amount to be an explicit nil
func (o *MutableOverTheCounter) SetAmountNil() {
	o.Amount.Set(nil)
}

// UnsetAmount ensures that no value is present for Amount, not even an explicit nil
func (o *MutableOverTheCounter) UnsetAmount() {
	o.Amount.Unset()
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *MutableOverTheCounter) GetCurrency() string {
	if o == nil || utils.IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MutableOverTheCounter) GetCurrencyOk() (*string, bool) {
	if o == nil || utils.IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *MutableOverTheCounter) HasCurrency() bool {
	if o != nil && !utils.IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *MutableOverTheCounter) SetCurrency(v string) {
	o.Currency = &v
}

// GetChannelCode returns the ChannelCode field value
func (o *MutableOverTheCounter) GetChannelCode() OverTheCounterChannelCode {
	if o == nil {
		var ret OverTheCounterChannelCode
		return ret
	}

	return o.ChannelCode
}

// GetChannelCodeOk returns a tuple with the ChannelCode field value
// and a boolean to check if the value has been set.
func (o *MutableOverTheCounter) GetChannelCodeOk() (*OverTheCounterChannelCode, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelCode, true
}

// SetChannelCode sets field value
func (o *MutableOverTheCounter) SetChannelCode(v OverTheCounterChannelCode) {
	o.ChannelCode = v
}

// GetChannelProperties returns the ChannelProperties field value
func (o *MutableOverTheCounter) GetChannelProperties() OverTheCounterChannelProperties {
	if o == nil {
		var ret OverTheCounterChannelProperties
		return ret
	}

	return o.ChannelProperties
}

// GetChannelPropertiesOk returns a tuple with the ChannelProperties field value
// and a boolean to check if the value has been set.
func (o *MutableOverTheCounter) GetChannelPropertiesOk() (*OverTheCounterChannelProperties, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelProperties, true
}

// SetChannelProperties sets field value
func (o *MutableOverTheCounter) SetChannelProperties(v OverTheCounterChannelProperties) {
	o.ChannelProperties = v
}

func (o MutableOverTheCounter) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MutableOverTheCounter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Amount.IsSet() {
		toSerialize["amount"] = o.Amount.Get()
	}
	if !utils.IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	toSerialize["channel_code"] = o.ChannelCode
	toSerialize["channel_properties"] = o.ChannelProperties
	return toSerialize, nil
}

type NullableMutableOverTheCounter struct {
	value *MutableOverTheCounter
	isSet bool
}

func (v NullableMutableOverTheCounter) Get() *MutableOverTheCounter {
	return v.value
}

func (v *NullableMutableOverTheCounter) Set(val *MutableOverTheCounter) {
	v.value = val
	v.isSet = true
}

func (v NullableMutableOverTheCounter) IsSet() bool {
	return v.isSet
}

func (v *NullableMutableOverTheCounter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMutableOverTheCounter(val *MutableOverTheCounter) *NullableMutableOverTheCounter {
	return &NullableMutableOverTheCounter{value: val, isSet: true}
}

func (v NullableMutableOverTheCounter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMutableOverTheCounter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


