openapi: 3.0.0
info:
  title: Xendit API
  version: 2.0.0
servers:
- description: Xendit API
  url: https://api.xendit.co
security:
- basicAuth: []
paths:
  /balance:
    get:
      parameters:
      - description: Account Type
        explode: true
        in: query
        name: account_type
        required: true
        schema:
          format: uuid
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Balance'
          description: success
      security:
      - basicAuth: []
      tags:
      - balances
components:
  schemas:
    Balance:
      example:
        balance: 0.8008281904610115
      properties:
        balance:
          type: number
      type: object
  securitySchemes:
    basicAuth:
      scheme: basic
      type: http
